package com.royalmaster.royalmaster.entities;
// Generated 23/10/2015 10:18:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Directores generated by hbm2java
 */
@Entity
@Table(name="directores"
    ,catalog="RoyalMaster"
)
public class Directores  implements java.io.Serializable {


     private Integer idDirector;
     private String nombreDirector;
     private Set peliculases = new HashSet(0);

    public Directores() {
    }

	
    public Directores(String nombreDirector) {
        this.nombreDirector = nombreDirector;
    }
    public Directores(String nombreDirector, Set peliculases) {
       this.nombreDirector = nombreDirector;
       this.peliculases = peliculases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDirector", unique=true, nullable=false)
    public Integer getIdDirector() {
        return this.idDirector;
    }
    
    public void setIdDirector(Integer idDirector) {
        this.idDirector = idDirector;
    }

    
    @Column(name="nombreDirector", nullable=false, length=45)
    public String getNombreDirector() {
        return this.nombreDirector;
    }
    
    public void setNombreDirector(String nombreDirector) {
        this.nombreDirector = nombreDirector;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="directores")
    public Set getPeliculases() {
        return this.peliculases;
    }
    
    public void setPeliculases(Set peliculases) {
        this.peliculases = peliculases;
    }




}


