package com.royalmaster.royalmaster.entities;
// Generated 23/10/2015 10:18:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfiles generated by hbm2java
 */
@Entity
@Table(name="perfiles"
    ,catalog="RoyalMaster"
)
public class Perfiles  implements java.io.Serializable {


     private Integer idPerfil;
     private String tipoUsuario;
     private Set usuarioses = new HashSet(0);

    public Perfiles() {
    }

	
    public Perfiles(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public Perfiles(String tipoUsuario, Set usuarioses) {
       this.tipoUsuario = tipoUsuario;
       this.usuarioses = usuarioses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPerfil", unique=true, nullable=false)
    public Integer getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }

    
    @Column(name="tipoUsuario", nullable=false, length=45)
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perfiles")
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


